---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jupyterhub-cluster-config-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgAmRxBdyujGIZJAqUFDuELGinhpZGAKbqHIYh8bAg/IyRMYkgCsfR25EKiJN9IvGEM9z9Bcq88iwQriNkn41EMEMz9NzhXYhJ8tn5UywIV37xLaRZGhHUlJ04wKcrGsr1FnsiQw0RnfyK2iJC4cUsHmZ4hLQu4r68/Fkp487kcRWmyBtzluIlDz5lEPkm95Ae5uNbt1Rwe3zb+9vbQGG89GJu6fVxYMbaxkKEyEgJx+kez95BkCtaCXbNz/uaknyGLucFjKYG09y7QHLeHbKIIzGkmfpVuZqm2otHuNpP3LtLpq0bCPOqDq+2eXu5XDz5SXNheVM+V62QkUF5/dFcynmSJsuuhxqfOzve+3zoze/I3Grm9gXvT4qgCFuVnBc0Fbwp8da0L84rQqG+v6nO/5M83zVIk1dooZQvg7sQEDOuFpcIUWHzLLiPso9dd5s4LPchp4cQAvvaYY760wZLpCPc+24ce9BbMipOpv6alWwz5EUlRuDk8WuqrheskqlhhserjBL5m1+HmrpreHQkBu9TYuZwRWD3rR2H3f3bkGhADM9+INT2cE6dk1RGSPb8zYu+c1+AVT776ejwm1HYviyAi2WnuOOLvwUCCl8kDGkUtkSyw/ozvZN7WoAtmveb6mhdOk4G4fIAu8qhZ09J/pRXmcMB34ZHuYth8flf59dEJueNhjhUOkLUgEMlwKsiwVxxzjOPXFbYqHf6r7WzhNotS92v+pLiJkv87Wr1JiiQRaAfzTdgnhNRITp4v+lntP4vZBLY5Vk84egZtdF1i/k8mFlePZ3s/uRA9bXnFRAhhfXVXdF2rqAhRBLinnvooNhH19T4UR8Uu6NVcJ5F+mnZKVNDq/kG2j3kFMsDiJN1VeWsylUpkBnzmP1tna3e+O2lRBc6ppEx7tkvsdD8z1nncgt/QHwAGfbQqFgEozCUuZEdAxuCpMDnbwueSYVJQ8L0p825QU7o/LQ5VOwq09922+40UHESAJxz9nxjvz17r9sxX3DzFuWhWVxSKcW8On6+fURS225eV3Kw4nCS7G6DMvtHElcAUGIequtmXeMqr5bqx9LQCtHtTFeMzKXw8mkjHNi2w30KLQwzVH3k6//Vlc6hBBFvxat0RMrilsl0NUxd4ZaMmDIYAShl9zb6W5KtG5R3AdpkLmMi0Jjain9MXvue0Z00peBeYkzaxZL6wx2urkI1mdd1jOmOg9/Vbg6ltXYiOB0iI91YAaw1+YKRui3kpU+9KL8mmRD1q0pzdpC3woNh9g//qjFp0aKRCug2Mq4Kpn3gtSPa6JT0BfzicaICcalPRAdI7W
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: jupyterhub-cluster-config-credentials
      namespace: capi-self
