---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: conch-config-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgCn111ypss9OjDFYiCzMsBga1NX1O6DuIFwkBGbeyIV4+5NhDrULWOMqwwJXZpuVGSF1+EM7rZNfbu+qGozk1p5IJS9xN//6KEC5I7k5vEpSP/+pVLyWqKwYF1UaDglWut79uUPvD2WYI8M4tNMtZE83vFzMsUrnniJBFsHk+j9BQPBjbzj2z16UzxXL9WQPt4QKkfvaDnqwHwTtlgM8FF3XE4InM/oSXWGPRDuqsJycMUTia6JJwYgiCFr5I/+XpmEjK0lzPG9QIMDud8nQ7+z/qupf27x19gmsHFK3rAIJEIxJo6t8TYIau9Lxa3OBgxYfGUadpnL4m5ty38AWlGyYFEx2lvjrldWXtXl14O6d5PCTijCr3hYYo2GgGWyvBeBfXyY0J0a+IZNGqCLGUb6JqaMJYGeipDYr9FTho2n+FfRwi0JHpkXKgRQ+wqm6ALw4JbFftkcrDxbRkOm56GTFo1aP6gZnXyKQ3AUyXs2c+PbKq8ODqhVbn32goLD4cTRbdfE022bTG4SpuWJXRIwdGzMW4u0KE2FA3Ogct0L9tqB8EBOLfQfUtgvjgv6x+gSt85GIufRFVj3zKLY73+SSc9LEcKWOeFmuSgyYJsaEMe3uxPVtlh6S21kXBxB7RAt61reoUiK9Lo90LbNCnSvh4J/0oS8c9WT+2kLH5sdQzVZdgsT1NYUjNtKjPE1urgIb1cJJg+TF/Om/jIhq1tyt7kqJybaTMX0sXvwLU0tdeWGzeJbFfA6SO5XwtL1EW2OYO3ne7mfYv58U3dqX+qaZS5ut4gTJVjN4uMc6xO7hED7+ybHkS7lGwSJL6Xvpo+qCk7k64Z5VqiswSj1ZkcTyRdL2pu0h2s/JK3Lj3RZlwiEQ3u/xF0yv3qI7CSFu72enFmA+RzZPsAVdA6qwm0fjhyLcU/BSWyccML/uVp1fvT3HTZNI0wAjZBKp2rp9qUsvscnA0Xl29cYTqNgii/I+NlHzCuEuqd6X0lx/I9RgEZCUjp6JVoBQyeIIJAU4kutqsp85r5NXfhPA3ll02Far5CLc5dcQ1uSKALCtWphpaZx+IRlHwXEoufutvmriTCu6N8RCCQAuecDNwYJM+heWtDNaCM/+8Bs/Woupql3zmD1sMzN2x8ecY4iaiYLhG63qjzZzr/gw6aFDp4oPbqWh97aQFO6cVg6Ouue1CRLQh0LGLqCPgly8xJP6Y8Bj58UAgKvclf5jlWFMvXL3btRUoos/0fg
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: conch-config-credentials
      namespace: capi-self
