---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: conch
  namespace: conch-fluxcd
spec:
  chart: conch
  version: 0.1.9
  sourceRef:
    kind: HelmRepository
    name: conch
  type: "oci"
  url: oci://ghcr.io/isambard-sc/charts/conch
  interval: 5m0s # Default was 1h
