---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-example-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgBRvj0wm26Wa74sL4GU872g4kujf4BOr8AI3iv/jnbnX56i4l3B3Ei0nUntN6LXPowX0YDBk7ZwBcDjXsbBfLteYvYmCBlgGnxPbaijuHrVOP06fgWoiGuuONugCKPVrWc4FDVUD84ojvuecrh72DyOCA9DTTepT9pl1RfXfZfnt241O48q2yy/rafhAAKrz14k/2msFel6rKVqM+9Jwq9RiAIKz8/FTQ2slVXwECvwhdGA0HUgqj9msYoPGIvPtjUDS4GjnJVlWZ29PPsIUYZYk3tfalSLJCEDcNUDzOWJRO0C3dqQ9xr3MsUhLWJUFDa5gv7NBTZoIQgk3EuQM1NHXLQAzxFLzsrUrcFa3XsBcPfBioUrgCfyf1FCNZ8/tqO+K0InSQkKe54uGPIbBlMJ0+wXPD2/G+VzsjKutaHrsP4iMk50teAs2De3fLEsxVfZ5bL66UpqcgTqkz36Ki848rUZZSOpIocGMCMgsMP+ifsMTHgVPsyRTsk+jKceajdZAtQLcNaH7wYnr3rdFYY3Js6Iqk3jZlpq0cJuuz+ZeBt8UIckx7Bx9PaO+w9kBtS8kmzCz2SqQJ8HAS0lozuRMr5OEdBkgWg57Vxklnxh/RWIqB+ECDonKL+99hiDLF7rAB4IFTS40gGIND99mC3wyLulC80I/4If6AhaOrU8/n/gskg34OMj71zolT+WH+MVgqo9On7yiYg5Bj9iee0ai7CqZdjpUKrtUOz5gn3DoyB/VJeBkafppKfg43sqee/a2fYghnbYc4qnLB6w+kdcpfw3rAL5r8fNMtuU6HgTSKfOmCEXA3r+e9uqFryt+uayDVMpBWwwEYz5UBo0UYax1R6dOKOknp2rBuastUfHEgvKBw/QNdPF4QjnhRTimgPJAXhvglld7w/HS6iRNeM3g8MowyvHF5UXYmq4XT/FLXdohiK0yEtcJzA5C8H6uNvFIIl5dXmStLSzEj/yEdjUbBc+3v9DafF5vjVIZqvhQUGNVrggJ00VUChZ+iE2XxhLzrmZPKtr95icqaAz2TVRwcY5pvvuDpBnE7PDxImWPdBbC5X1GNltgFRojLAwCeEhEAEI/t1MTqvzBgrd3jtBgTYcArynUaImz+351Q1qFEGm8mD/w0A844F5e3dI/ECwsyZifteqy8+VbiGUITccth90/yvZ79sTCGzFA8rAsLEh3LvboiXwNa7bmtmWxG7ooKYcRpLJBMGL8rsbcrzu35Tf2SJvZ18+hibDTWg+jie2faoTIbNTazthpF4LSyurBOmittGNcAG8p4ZQP5kcHnA55v4NKwh0i40=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: cluster-example-credentials
      namespace: capi-self
