---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-example-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgBM+2zkP4VEjLHXNK3uQzyzwi3Fm9ZSvQ2na6f/Zg+/+CR7aLvA7Zps9ngP3jEFscV/FSRYqFIeANHdWcGpMyMY5UBS7k/6gx81dY3mfdbsfv+v3Snn7QSZlY5mN0/BhlgD5QkbPqG/Js2++Ae9fOxULefrRofrbS/1og+4Sy+LN1BpS11Q+l1OIe9KvMmPwzWvP2RaBAagZoDuVcL6dWUYxl3e+iI9ynYoJaoctUf7UiE0q2DnPTTatRkmkBqal4cfTVJ0HNTztDCpfO6yyv/4b/3G9MRyv0kJk2Eij87QXerRdv1x6DS9S7QozKNdyx/TzjevCoi3OuGhZCgqgOEaXm0aIS25zXEbMZZ7mmeZqLHGnCJpQrhC+GvQ91zNxArnPY3ihPSChg+48z3uay3qmb3yT/eVoMt/XwGa85KJx6hPZN10Y6ij70d1txJ1EKN4NM3FSb3/AXg1jwBSsKRpByc8u16obbbqZ21dAN1ZXIWqNZ1hnLJ37mZlhynRq9JJP4x1YYa5ENsLc1LfVcF1mbGIoCkc6FRNy6Db35AfVQLmOfrU89CYjE/spGoxNlmDZrRH9aOrpIitjFOmsY8XzgpMYn6sQf9MHj0KACROGt7Kcrx+YweDKuyymr0Sn/XZL+oLs98xzLAcKptKDG69LAMUUQFHoSCBcmEJKnnLvESZzSDybB8nP54jCJff7duKQUev2jUcZK6gCZsNjlr+LdTx/V/rttz+JWYnxcIU+JbHeYI5RBd6d+aFJvORXdr4GuyrCthp9rNslhpn0BTAzOURbKATI5ShefJxyabC7O9xjMsnidYTk3Olp2ZdBH2o6AYbx2lezooJ+5o9WLjiGhfLAVIq6L9sWSBDLUUpoTDsNhA9RzXSCLia1euKRZ+flu2U+JbE9xYq4SG+pwGUtiA/rRn8hbHeR2LSyufqhIHRsWFdEP3tfohzA6jBQ+9JXftvGq6XnguVDWlN60AgOV6LYHNLL7P8B8OuRroB+Ge7lVyRuuYULz/x9ZPrLCP5njtiwNlOsxAHUr5e9EW1PBbVoPzPus0YYEbwfGFVOV9fkb2R3K4eMLhinND3w1l+7vGvqPhWUUZponx39610855+IIQtxj550T8kV2tJJgp/5Xizg/KJPnbS1uokfTaq8RisGPCLHghAhwMVBpHyBpq+TT+Orutbq+vBqV1JxfRloyyVJOM8AWd0P0cM+Zx4R7UIBj6Xa/aRC2s0ksJvjfkBfE+i
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: cluster-example-credentials
      namespace: capi-self
