---
############
# IMPORTANT: Make sure you run kubeseal against any secret before commiting it to git!
# Example command:
# kubeseal \
#   --kubeconfig clusters/jupyterhub/kubeconfig \
#   --format yaml \
#   --controller-name sealed-secrets \
#   --controller-namespace sealed-secrets-system \
#   --secret-file components/jupyterhub/secret.yaml \
#   --sealed-secret-file components/jupyterhub/secret.yaml
############
apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-keycloak-config
  namespace: jupyterhub
stringData:
  keycloakClientSecret: <keycloak-client-secret>
