---
############
# IMPORTANT: Make sure you run kubeseal against any secret before commiting it to git!
############
apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-keycloak-config
  namespace: jupyterhub
stringData:
  keycloakClientId: <keycloak-client-name>
  keycloakClientSecret: <keycloak-client-secret>
  keycloakDiscoveryUrl: <keycloak-realm-url>/.well-known/openid-configuration
