---
############
# IMPORTANT: Make sure you run kubeseal against any secret before commiting it to git!
############
apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-keycloak-config
  namespace: jupyterhub
stringData:
  keycloakClientSecret: <keycloak-client-secret>
