---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  chart: jupyterhub
  version: 4.0.0
  sourceRef:
    kind: HelmRepository
    name: jupyterhub
  interval: 1h
