---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: intel-device-plugins-for-kubernetes
  namespace: intel
spec:
  interval: 5m
  url: https://github.com/intel/intel-device-plugins-for-kubernetes
  ref:
    tag: v0.30.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-rules
  namespace: intel
spec:
  interval: 10m
  targetNamespace: intel
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins-for-kubernetes
  path: deployments/nfd/overlays/node-feature-rules/
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operator
  namespace: intel
spec:
  interval: 10m
  targetNamespace: intel
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins-for-kubernetes
  path: deployments/operator/default
  prune: true
  timeout: 1m
