---
apiVersion: v1
kind: ConfigMap
metadata:
  name: waldur-config
  namespace: waldur
data:
  values.yaml: |

    postgresql:
      enabled: true
    rabbitmq:
      enabled: true

    ### Example config for exposing the Waldur UI via sslio.io

    # NOTE: This host IP must match the FIP which was assigned
    # to the NGINX ingress controller's load balancer.

    # apiHostname: 128-232-226-47.sslip.io
    # apiScheme: https
    # homeportHostname: 128-232-226-47.sslip.io
    # homeportScheme: https
    # ingress:
    #   tls:
    #     enabled: true
    #     source: letsEncrypt

    ### Example config for Keycloak integration

    # waldur:
    #   authMethods:
    #   - LOCAL_SIGNIN
    #   - SOCIAL_SIGNUP
    #   socialAuthMethods:
    #   - label: Keycloak
    #     provider: keycloak
    #     # clientId: <stored-in-sealed-secret>
    #     # clientSecret: <stored-in-sealed-secret>
    #     # discoveryUrl: <stored-in-sealed-secret>
    #     managementUrl: ""
    #     protectedFields:
    #     - full_name
    #     - email
