---
apiVersion: v1
kind: Secret
metadata:
  name: waldur-keycloak-config
  namespace: waldur
stringData:
  values.yaml: |
    socialAuthMethods:
    - clientId: "<keycloak-client-name>"
      clientSecret: "<keycloak-client-secret>"
      discoveryUrl: "<keycloak-realm-url>/.well-known/openid-configuration"
      label: Keycloak
      managementUrl: ""
      protectedFields:
      - full_name
      - email
      provider: keycloak
