---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-infra
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ../../components/cert-manager
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-clusterissuer-config
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-infra
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ../../components/cluster-issuer
  prune: true
  patches:
    - patch: |
        - op: add
          path: /spec/acme/email
          value: test@email.com
      target:
        kind: ClusterIssuer
        name: letsencrypt