name: Publish Container Images
on:
  push:
    paths:
      - images/**
jobs:
  build_push_images:
    name: Build and push images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: jupyterhub-intel-gpu
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate metadata for image
        id: image-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/stackhpc/${{ matrix.image }}
          # Produce the branch name or tag and the SHA as tags
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=

      - name: Build and push image
        uses: azimuth-cloud/github-actions/docker-multiarch-build-push@master
        with:
          cache-key: ${{ matrix.image }}
          context: ./images/${{ matrix.image }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.image-meta.outputs.tags }}
          labels: ${{ steps.image-meta.outputs.labels }}
